apiVersion: v1
kind: Pod
metadata:
  name: ub-pod
  labels:
    app: ub-pod
  annotations:
    v1.multus-cni.io/default-network: sriov-ovn-1
spec:
  containers:
  - image: shaharklein/ub-gen:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: ub-pod
    resources:
     requests:
       intel.com/sriov: '1'
     limits:
       intel.com/sriov: '1'
