- hosts: kube-master
  become: yes
  gather_facts: false
  tasks:
    - name: swap off
      shell: swapoff -a
      
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: kube-node
  become: yes
  tasks:
    - name: swap off
      shell: swapoff -a

    - name: reset node
      shell: kubeadm reset -f
    - name: join cluster
      shell: "{{ hostvars[groups['kube-master'][0]].join_command }}"
      #shell: "{{ hostvars['ip10921280'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME

