- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Assign inventory name to hostnames
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Add hostname resolv
      #debug:
      #msg: "{{ ansible_host }}"
      lineinfile: 
        dest: /etc/hosts
        line: "{{ ansible_host }} {{ inventory_hostname }}"
        state: present
